# List of .mif files
roi_list = [
    "wm_fod.mif",
    "AF_L.mif",
    "AF_R.mif",
    "SLF_L.mif",
    "SLF_R.mif",
    "BROCA_L.mif",
    "BROCA_R.mif",
    "AF_exclude.mif",
    "R_Ped.mif",
    "L_Ped.mif",
    "RHandM1.mif",
    "LHandM1.mif",
    "R_Cap.mif",
    "L_Cap.mif",
    "SHA_L.mif",
    "SHA_R.mif",
    "RHandS1.mif",
    "LHandS1.mif",
    "R_Thal.mif",
    "L_Thal.mif",
    "LipM1.mif",
    "L_LGN.mif",
    "R_LGN.mif",
    "L_latCalc.mif",
    "R_latCalc.mif",
    "L_latVentr.mif",
    "R_latVentr.mif",
]

# List of .tck files
tck_list = [
    "mrtrix3-AF_L.tck",
    "mrtrix3-AF_R.tck",
    "mrtrix3-AF_EX.tck",
    "mrtrix3-MHA_R.tck",
    "mrtrix3-MHA_L.tck",
    "mrtrix3-MHA_R.tck",
    "mrtrix3-MHA_L.tck",
    "mrtrix3_R_Lip.tck",
    "mrtrix3_L_Lip.tck",
    "mrtrix3_L_OR_UNI.tck",
    "mrtrix3_R_OR_UNI.tck",
]
